### ISSUE TITLE
Idea: Show samples within commandlet doc

### ISSUE THREAD

**Issue by pkbullock** [Adam-it/pnp-powershell-extension#6]
Hi Adam,

In the cmdlet view, is it possible to filter and show related samples? I do tag samples within the tags element of the samples.json - CLI cmds as well. 

![image](https://user-images.githubusercontent.com/8781041/189474984-5877f332-6a2c-4364-97b5-c0b9c310f3ab.png)

**Comment by Adam-it** [comment]
hmm.. not sure If I understand the idea fully so let's discuss it a bit. 🙂
So from what I understand we could add some kind of button like "show related samples" in the docs view of the cmdlet. 
![image](https://user-images.githubusercontent.com/58668583/189477886-fc58eac0-ea55-48f2-90f2-4592e1233f65.png)

When user would click on this button the sample view would open in the editor showing the samples that use this cmdlet?
Did I understand this correctly ? would this behavior be ok ?
This would also fit nicely with other functionality I plan to add which is a button in the docs view which would open that doc page in browser so the user with single click would land on the correct page of PnP PS docs (or CLI as those extension actually have 90% same code base 😉)

**Comment by Adam-it** [comment]
@pkbullock any additional comments on this one? Seems that this is quite clear for me I would just like to confirm 😉

**Comment by pkbullock** [comment]
Yeah either show related samples or I was originally thinking show the sample cards at the bottom of the page BUT, what if there are loads so a button to navigate to samples probably the best.

**Comment by Adam-it** [comment]
showing the sample cards at the bottom of the docs page will introduce additional complexity which might be confusing for the user. Also the docs tend to be quite long (especially the list of parameters/options for a command), so the user might not always 'scroll down' to the bottom to actually see there are some samples related there.
If the button is fine with you then I think this is the approach I will take 🙂💪.

ok all clear 👍.
I will plan it to be done in the next development time for this extension.
Thanks @pkbullock for this awesome idea 🤩🤩
